routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FollowerController;
use App\Http\Controllers\LikedPostController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/register", function () {
    return view("auth.register");
})->name("register.view");

Route::get("/login", function () {
    if (Auth::check()) {
        return redirect()->route("home");
    } else {
        return view("auth.login");
    }
})->name("login");

Route::controller(UserController::class)->group(function () {
    Route::post("/register", "store")->name("register.post");

    Route::get("/activate/{token}", "activation")->name("activation");

    Route::post("/resend-activation", "resendActivation")->name("resend-activation");

    Route::post("/login", "login");
});

Route::middleware(["auth"])->group(function () {
    Route::get("/", [PostController::class,"index"])->name("home");

    Route::controller(UserController::class)->group(function () {
        Route::get("/search/users", "search")->name("users.search");
        Route::patch("/change-password/{user}", "updatePassword")->name("users.change-password");
    });

    Route::resource("users", UserController::class)->only([
        "show","edit","update"
    ]);

    Route::controller(FollowerController::class)->group(function () {
        Route::get("/{id}/followers", "follow")->name("users.followers");
        Route::get("/{id}/following", "follow")->name("users.following");
        Route::post("follow", "store")->name("follow");
        Route::delete("follow", "destroy")->name("unfollow");
    });

    Route::controller(PostController::class)->group(function () {
        Route::get("/search/posts", "search")->name("posts.search");
    });

    Route::resource("posts", PostController::class)->except([
        "index",
        "create"
    ]);



    Route::resource("comments", CommentController::class)->except([
        "index", "create", "show"
    ]);
    Route::resource("likes", LikedPostController::class)->only([
        "store","destroy"
    ]);



    Route::post("/logout", [UserController::class,"logout"])->name("logout");
});

app/Models/User.php
<?php

namespace App\Models;

use Hash;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    protected $fillable = [
        'first_name',
        'last_name',
        'middle_name',
        'username',
        'birthday',
        'email',
        'password',
    ];

    protected $hidden = [
        'password',
        'verification_token',
    ];
    /**
     * Get if Followed By User
     *
     * @return boolean
     */
    public function getIsFollowedByUserAttribute()
    {
        $userId = auth()->user()->id;

        return $this->followers()->where("user_id", $userId)->count() > 0;
    }
    /**
     * No. of followers
     *
     * @return integer
     */
    public function getNoOfFollowersAttribute()
    {
        return $this->followers()->count();
    }
    /**
     * No. of following
     *
     * @return integer
     */
    public function getNoOfFollowingAttribute()
    {
        return $this->followings()->count();
    }
    /**
     * Full Name Attribute
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->middle_name) . ' ' . ucfirst($this->last_name);
    }
    /**
     * Hashing password before storing in database
     *
     * @param string $value
     * @return void
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }
    /**
     * Posts of user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function posts()
    {
        return $this->hasMany(Post::class);
    }
    /**
     * Comments of user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
    /**
     * Followers of user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function followers()
    {
        return $this->hasMany(Follower::class, "following_user_id");
    }
    /**
     * Following of user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function followings()
    {
        return $this->hasMany(Follower::class);
    }
    /**
     * Liked Post of user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function likes()
    {
        return $this->hasMany(LikedPost::class);
    }
    /**
     * Deleting posts, comments, followers, following & liked post when deleting user
     *
     * @return void
     */
    public static function boot()
    {
        parent::boot();
        static::deleting(function ($user) {
            $user->posts()->delete();
            $user->comments()->delete();
            $user->followers()->delete();
            $user->followings()->delete();
            $user->likedPost()->delete();
        });
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Hash;
use App\Http\Requests\LoginRequest;
use Mail;
use App\Http\Requests\RegisterUserRequest;
use App\Http\Requests\ResendActivationRequest;
use App\Http\Requests\SearchRequest;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\UpdatePasswordRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\User;
use App\Mail\UserMail;

class UserController extends Controller
{
    /**
    * Using the built-in middleware of Policy so that only the owner can edit and delete
    **/
    public function __construct()
    {
        $this->middleware("can:delete,user")->only(['edit','delete']);
    }
    /**
     * This is to show the details of the user including his/her posts/follower/following
     *
     * @param User $user
     * @return \Illuminate\Contracts\View\View
     */
    public function show(User $user)
    {
        $owner = ($user->id == Auth::user()->id);
        $posts = $user->posts()->orderBy('created_at', 'desc')->paginate(5);

        return view("users.show", compact("user", "owner", "posts"));
    }
    /**
     * This is to show the details of a single user for editing
     *
     * @param User $user
     * @return \Illuminate\Contracts\View\View
     */
    public function edit(User $user)
    {
        return view("users.edit", compact("user"));
    }
    /**
     * Update the personal details of a user
     *
     * @param UpdateUserRequest $req
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateUserRequest $req, User $user)
    {
        $safe = $req->safe();
        if (!empty($safe->profile_pic)) {
            $path = $safe->profile_pic->store('public/images/users');
            if ($user->profile_pic) {
                Storage::delete($user->profile_pic);
            }
            $user->profile_pic = $path;
        }
        if (isset($req->rem_image)) {
            Storage::delete($user->profile_pic);
            $user->profile_pic = null;
        }
        $user->email = $safe->email;
        $user->username = $safe->username;
        $user->last_name = $safe->last_name;
        $user->first_name = $safe->first_name;
        $user->middle_name = $safe->middle_name;
        $user->birthday = $safe->birthday;
        $user->save();

        return back()->with("details", "User Details Updated!");
    }
    /**
     * Update Password
     *
     * @param UpdatePasswordRequest $req
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function updatePassword(UpdatePasswordRequest $req, User $user)
    {
        $validated = $req->safe();
        if (password_verify($validated->old_password, Auth::user()->password)) {
            $user->password = $validated->password;
            $user->save();

            return back()->with("change_pass", "Password Updated!");
        } else {
            return back()->with("old_password", "Wrong password!");
        }
    }
    /**
     * Register user and sending the activation link after registration
     *
     * @param RegisterUserRequest $req
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(RegisterUserRequest $req)
    {
        $safe = $req->safe();
        $user = new User();
        $user->email = $safe->email;
        $user->username = $safe->username;
        $user->last_name = $safe->last_name;
        $user->first_name = $safe->first_name;
        $user->middle_name = $safe->middle_name;
        $user->birthday = $safe->birthday;
        $user->password = $safe->password;
        $token = base64_encode($user->id . "@" . date("Y-m-d H:i:s", strtotime('+4 hours')));
        $user->verification_token = $token;
        $user->save();
        $mailData = [
            "title" => "User Activation",
            "body" => url("activate/" . $token)
        ];
        Mail::to($user->email)->send(new UserMail($mailData));

        return redirect()
        ->route('register.view')
        ->with('success', 'Please check your email address for the confirmation link.');
    }
    /**
     * Activating User
     *
     * @param string $token
     * @return \Illuminate\Contracts\View\View
     */
    public function activation($token)
    {
        $user = User::where("verification_token", $token)->first();
        $msg = "";
        $id = 0;
        if ($user) {
            $tmp_token = explode("@", base64_decode($token));

            $id = $tmp_token[0];
            $exp = $tmp_token[1];
            if (!empty($user->verified_at)) {
                $msg = "Unknown activation code!";
            } else {
                if (date("Y-m-d H:i:s") <= $exp) {
                    $msg = "Account Successfully Activated!";
                    $user->verified = true;
                    $user->verification_token = "";
                    $user->save();
                } else {
                    $msg = "Activation Link Expired!";
                }
            }
        } else {
            $msg = "Unknown activation code!";
        }

        return view('users.activate', compact("msg", "id"));
    }
    /**
     * Resending a valid token to the user
     *
     * @param ResendActivationRequest $req
     * @return \Illuminate\Http\RedirectResponse
     */
    public function resendActivation(ResendActivationRequest $req)
    {
        $safe = $req->safe();
        $user = User::find($safe->id);
        if ($user) {
            $token = base64_encode($user->id . "@" . date("Y-m-d H:i:s", strtotime('+4 hours')));
            $user->verification_token = $token;
            $user->save();
            $mailData = [
                'title' => 'User Activation',
                'body' => 'http://' . Request()->getHttpHost() . "/activate/" . $token
            ];
            Mail::to($user->email)->send(new UserMail($mailData));

            return redirect()
            ->route('register.view')
            ->with('success', 'Please check your email address for the confirmation link.');
        }
    }
    /**
     * Login function
     *
     * @param LoginRequest $req
     * @return \Illuminate\Http\RedirectResponse
     */
    public function login(LoginRequest $req)
    {
        $safe = $req->safe();
        if (
            Auth::attempt(
                array(
                'username' => $safe->username,
                'password' => $safe->password,
                'verified' => 1
                )
            )
        ) {
            return redirect()->route('home');
        } else {
            return back()->with('warning', 'Wrong username/password!')->onlyInput('username');
        }
    }
    /**
     * Logout function
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function logout()
    {
        Auth::logout();
        session()->invalidate();
        session()->regenerateToken();

        return redirect()->route('login');
    }
    /**
     * Undocumented function
     *
     * @param SearchRequest $req
     * @return \Illuminate\Contracts\View\View
     */
    public function search(SearchRequest $req)
    {
        $search = htmlentities($req->safe()->q);
        $users = User::whereRaw(
            '(LOWER(first_name) LIKE ? OR LOWER(middle_name) LIKE ? OR LOWER(last_name) LIKE ?) AND id!=?',
            ["%{$search}%","%{$search}%","%{$search}%",Auth::user()->id]
        )->paginate(5);

        return view("users.search", compact("users", "search"));
    }
}

resources/views/users/activate.blade.php
@extends('layouts.main')
@section('title', 'User Activation')
@section('content')
    <div class="row">
        <div class="col">
            <h1 class="text-primary mt-4 mx-4">MicroBlog</h1>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-12 col-md-3 col-lg-3 text-center">
            @include('flash_message')
            <h1>{{ $msg }}</h1>
            @if ($msg == 'Account Successfully Activated!')
                <p>
                    Thank you for registering on our platform.
                </p>
                <br>
                <a class="btn btn-success mt-2" href="{{ route('login') }}">Login Now!</a>
            @elseif($msg == 'Activation Link Expired!')
                <br>
                <form method="post" action="{{ route('resend-activation') }}">
                    @csrf
                    <input type="hidden" name="id" value="{{ $id }}" />
                    <button class="btn btn-primary" type="submit">
                        Resend Activation Link
                    </button>
                </form>
            @else
                <a class="btn btn-success mt-2" href="{{ route('register.view') }}">Register Here</a>
            @endif
        </div>
    </div>
@endsection

resources/views/users/follow.blade.php
@extends('layouts.dashboard')
@if (isset($followers) && empty($name))
    @section('title', 'Followers')
@elseif(isset($followers) && !empty($name))
    @section('title', 'Followers | ' . $name)
@elseif(isset($followings) && !empty($name))
    @section('title', 'Following | ' . $name)
@else
    @section('title', 'Following')
@endif
@section('main_content')
    <div class="row">
        <div class="col">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            @else
                @include('flash_message')
            @endif
        </div>
    </div>
    @if (isset($followers))
        @if ($followers->count() > 0)
            @foreach ($followers as $follower)
                <div class="row mt-4">
                    <div class="col-12 col-md-3 col-lg-2 px-5 d-flex align-items-center">
                        <img class="img-fluid rounded-circle mt-4"
                            src="
      						@if ($follower->user->profile_pic) {{ Storage::url($follower->user->profile_pic) }} 
							@else 
							{{ 'https://res.cloudinary.com/dfv2lwp9b/image/upload/v1650258536/user-ph_nyau61.jpg' }} @endif"
                            alt="">
                    </div>
                    <div class="col">
                        <div class="row">
                            <div class="col mt-4">
                                <a class="link-dark" href="{{ route('users.show', ['user' => $follower->user->id]) }}">
                                    <h2>
                                        {{ $follower->user->full_name }}
                                    </h2>
                                </a>
                                <span class="fs-5">
                                    <a href="{{ route('users.following', ['id' => $follower->user->id]) }}">
                                        <b>
                                            {{ $follower->user->no_of_following }}
                                        </b>
                                    </a>&nbsp;Following
                                    &nbsp;&nbsp;&nbsp;
                                    <a href="{{ route('users.followers', ['id' => $follower->user->id]) }}">
                                        <b>
                                            {{ $follower->user->no_of_followers }}
                                        </b>
                                    </a>&nbsp;Followers
                                </span>
                            </div>
                        </div>
                        <div class="row mt-3 mb-4">
                            <div class="col">
                                @if ($follower->is_followed_by_user)
                                    <form method="post" action="{{ route('unfollow') }}">
                                        @csrf
                                        @method("DELETE")
                                        <input type="hidden" name="following_user_id"
                                            value="{{ $follower->user->id }}" />
                                        <button type="submit" class="btn btn-primary">
                                            <i class="bi bi-check-all"></i>
                                            &nbsp;&nbsp;Unfollow
                                        </button>
                                    </form>
                                @else
                                    <form method="post" action="{{ route('follow') }}">
                                        @csrf
                                        <input type="hidden" name="following_user_id"
                                            value="{{ $follower->user->id }}" />
                                        <button type="submit" class="btn btn-success">
                                            <i class="bi bi-bell-fill"></i>
                                            &nbsp;&nbsp;Follow
                                        </button>
                                    </form>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
            <hr>
            <div class="row">
                <div class="col">
                    {!! $followers->withQueryString()->links('pagination::bootstrap-5') !!}
                </div>
            </div>
        @else
            <h1 class="fw-bold text-center">No followers yet.</h1>
        @endif
    @else
        @if ($followings->count() > 0)
            @foreach ($followings as $following)
                <div class="row mt-4">
                    <div class="col-12 col-md-3 col-lg-2 px-5 d-flex align-items-center">
                        <img class="img-fluid rounded-circle mt-4" src="
							@if ($following->userFollow->profile_pic) 
							{{ Storage::url($following->userFollow->profile_pic) }}
							@else 
							{{ 'https://res.cloudinary.com/dfv2lwp9b/image/upload/v1650258536/user-ph_nyau61.jpg' }} 
							@endif
							" alt="">
                    </div>
                    <div class="col">
                        <div class="row">
                            <div class="col mt-4">
                                <a class="link-dark"
                                    href="{{ route('users.show', ['user' => $following->userFollow->id]) }}">
                                    <h2>
                                        {{ $following->userFollow->full_name }}
                                    </h2>
                                </a>
                                <span class="fs-5">
                                    <a href="{{ route('users.following', ['id' => $following->userFollow->id]) }}">
                                        <b>
                                            {{ $following->userFollow->no_of_following }}
                                        </b>
                                    </a>&nbsp;Following
                                    &nbsp;&nbsp;&nbsp;
                                    <a href="{{ route('users.followers', ['id' => $following->userFollow->id]) }}">
                                        <b>
                                            {{ $following->userFollow->no_of_followers }}
                                        </b>
                                    </a>&nbsp;Followers
                                </span>
                            </div>
                        </div>
                        <div class="row mt-3 mb-4">
                            <div class="col">
                                <form method="post" action="{{ route('unfollow') }}">
                                    @csrf
                                    @method("DELETE")
                                    <input type="hidden" name="following_user_id"
                                        value="{{ $following->userFollow->id }}" />
                                    <button type="submit" class="btn btn-primary">
                                        <i class="bi bi-check-all"></i>
                                        &nbsp;&nbsp;Unfollow
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
            <hr>
            <div class="row">
                <div class="col">
                    {!! $followings->withQueryString()->links('pagination::bootstrap-5') !!}
                </div>
            </div>
        @else
            <h1 class="fw-bold text-center">Not following anyone yet.</h1>
        @endif
    @endif
@endsection