routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FollowerController;
use App\Http\Controllers\LikedPostController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/register", function () {
    return view("auth.register");
})->name("register.view");

Route::get("/login", function () {
    if (Auth::check()) {
        return redirect()->route("home");
    } else {
        return view("auth.login");
    }
})->name("login");

Route::controller(UserController::class)->group(function () {
    Route::post("/register", "store")->name("register.post");

    Route::get("/activate/{token}", "activation")->name("activation");

    Route::post("/resend-activation", "resendActivation")->name("resend-activation");

    Route::post("/login", "login");
});

Route::middleware(["auth"])->group(function () {
    Route::get("/", [PostController::class,"index"])->name("home");

    Route::controller(UserController::class)->group(function () {
        Route::get("/search/users", "search")->name("users.search");
        Route::patch("/change-password/{user}", "updatePassword")->name("users.change-password");
    });

    Route::resource("users", UserController::class)->only([
        "show","edit","update"
    ]);

    Route::controller(FollowerController::class)->group(function () {
        Route::get("/{id}/followers", "follow")->name("users.followers");
        Route::get("/{id}/following", "follow")->name("users.following");
        Route::post("follow", "store")->name("follow");
        Route::delete("follow", "destroy")->name("unfollow");
    });

    Route::controller(PostController::class)->group(function () {
        Route::get("/search/posts", "search")->name("posts.search");
    });

    Route::resource("posts", PostController::class)->except([
        "index",
        "create"
    ]);



    Route::resource("comments", CommentController::class)->except([
        "index", "create", "show"
    ]);
    Route::resource("likes", LikedPostController::class)->only([
        "store","destroy"
    ]);



    Route::post("/logout", [UserController::class,"logout"])->name("logout");
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    /**
     * No. of likes
     *
     * @return integer
     */
    public function getNoOfLikesAttribute()
    {
        return $this->likes()->count();
    }
    /**
     * Get if the user liked the post
     *
     * @return void
     */
    public function getLikedByUserAttribute()
    {
        $userId = auth()->user()->id;
        $like = $this->likes()->select("id")->where("user_id", "=", $userId)->first();

        return $like;
    }
    /**
     * Details of shared post
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function sharedPost()
    {
        return $this->belongsTo(Post::class, "shared_post_id");
    }
    /**
     * Comments of post
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
    /**
     * Owner of post
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, "user_id");
    }
    /**
     * All likes of post
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function likes()
    {
        return  $this->hasMany(LikedPost::class);
    }
    /**
     * Deleting Likes and Comments when post is deleted
     *
     * @return void
     */
    public static function boot()
    {
        parent::boot();
        static::deleting(function ($post) {
            $post->likes()->delete();
            $post->comments()->delete();
        });
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Hash;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    protected $fillable = [
        'first_name',
        'last_name',
        'middle_name',
        'username',
        'birthday',
        'email',
        'password',
    ];

    protected $hidden = [
        'password',
        'verification_token',
    ];
    /**
     * Get if Followed By User
     *
     * @return boolean
     */
    public function getIsFollowedByUserAttribute()
    {
        $userId = auth()->user()->id;

        return $this->followers()->where("user_id", $userId)->count() > 0;
    }
    /**
     * No. of followers
     *
     * @return integer
     */
    public function getNoOfFollowersAttribute()
    {
        return $this->followers()->count();
    }
    /**
     * No. of following
     *
     * @return integer
     */
    public function getNoOfFollowingAttribute()
    {
        return $this->followings()->count();
    }
    /**
     * Full Name Attribute
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->middle_name) . ' ' . ucfirst($this->last_name);
    }
    /**
     * Hashing password before storing in database
     *
     * @param string $value
     * @return void
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }
    /**
     * Posts of user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function posts()
    {
        return $this->hasMany(Post::class);
    }
    /**
     * Comments of user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
    /**
     * Followers of user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function followers()
    {
        return $this->hasMany(Follower::class, "following_user_id");
    }
    /**
     * Following of user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function followings()
    {
        return $this->hasMany(Follower::class);
    }
    /**
     * Liked Post of user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function likes()
    {
        return $this->hasMany(LikedPost::class);
    }
    /**
     * Deleting posts, comments, followers, following & liked post when deleting user
     *
     * @return void
     */
    public static function boot()
    {
        parent::boot();
        static::deleting(function ($user) {
            $user->posts()->delete();
            $user->comments()->delete();
            $user->followers()->delete();
            $user->followings()->delete();
            $user->likedPost()->delete();
        });
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use App\Models\Follower;
use App\Models\Post;
use App\Http\Requests\SearchRequest;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\StorePostRequest;
use App\Http\Requests\UpdatePostRequest;

class PostController extends Controller
{
    /**
    * Using the built-in middleware of Policy so that only the owner can edit and delete
    **/
    public function __construct()
    {
        $this->middleware("can:delete,post")->only(['edit','delete']);
    }
    /**
     * Search Users function
     *
     * @param SearchRequest $req
     * @return \Illuminate\Contracts\View\View
     */
    public function search(SearchRequest $req)
    {
        $safe = $req->safe();
        $search = htmlentities(strtolower($safe->q));
        $followings = Follower::where("user_id", "=", Auth::user()->id)->pluck('following_user_id');
        $followings = $followings->merge([Auth::user()->id]);
        $posts = Post::whereIn("user_id", $followings->all())
        ->whereRaw("LOWER(content) LIKE ?", ["%{$search}%"])->orderByDesc("created_at")->paginate(5);

        return view("users.search", compact("posts", "search"));
    }
    /**
     * Showing of posts and followed users posts
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index()
    {
        $followings = Follower::where("user_id", "=", Auth::user()->id)->pluck('following_user_id');
        $followings = $followings->merge([Auth::user()->id]);
        $posts = Post::whereIn("user_id", $followings->all())->orderByDesc("created_at")->paginate(5);

        return view("home", compact("posts"));
    }
    /**
     * Storing post
     *
     * @param StorePostRequest $req
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StorePostRequest $req)
    {
        $post = new Post();
        $safe = $req->safe();
        if (!empty($safe->shared_post_id)) {
            $content = $safe->shared_content;
            $post->shared_post_id = $safe->shared_post_id;
        } else {
            if (!empty($safe->image)) {
                $path = $safe->image->store('public/images/posts');
                $post->image = $path;
            }
            $content = $req->content;
        }
        $post->content = $content;
        $post->user_id = Auth::user()->id;
        $post->save();

        return redirect()->route("home")->with("success", "Posted successfully!");
    }
    /**
     * Fetching the details of a certain post
     *
     * @param Post $post
     * @return \Illuminate\Contracts\View\View
     */
    public function show(Post $post)
    {
        $comments = $post->comments()->orderByDesc("created_at")->paginate(5);

        return view(
            "posts.show",
            compact("post", "comments")
        );
    }
    /**
     * Fetching the details of a certain post for editing
     *
     * @param Post $post
     * @return \Illuminate\Contracts\View\View
     */
    public function edit(Post $post)
    {
        return view('posts.edit', compact("post"));
    }
    /**
     * Updating of post including deleting of old image if replaced
     *
     * @param UpdatePostRequest $req
     * @param Post $post
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdatePostRequest $req, Post $post)
    {
        $safe = $req->safe();
        if (!empty($safe->image)) {
            $path = $safe->image->store('public/images/posts');
            if ($post->image) {
                Storage::delete($post->image);
            }
            $post->image = $path;
        }
        if (isset($safe->rem_image)) {
            Storage::delete($post->image);
            $post->image = null;
        }
        if (isset($safe->rem_post)) {
            $post->shared_post_id = null;
        }
        $post->content = $safe->content;
        $post->save();

        return redirect()->route(
            'posts.show',
            [
                'post' => $post->id
            ]
        )->with("success", "Post Updated!");
    }
    /**
     * Deletion of post
     *
     * @param Post $post
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect()->route("home")->with("success", "Post Deleted!");
    }
}

resources/views/posts/edit.blade.php
@extends("layouts.dashboard")
@section("title","Edit Post")
@section("main_content")
<br>
<form method="post" 
    action="{{ route("posts.update",["post" => $post->id]) }}" 
    enctype="multipart/form-data" class="container-fluid">
    @csrf
    @method("PATCH")
    <div class="row">
        <div class="col mb-3">
            @include("flash_message")
            <textarea 
            class="form-control @error("content") {{ "is-invalid" }} @enderror" 
            id="content" 
            rows="8" 
            name="content">@if(old("content")){{ old("content") }}@else{{ $post->content }}@endif</textarea>
            <div class="text-danger mt-1">@error("content") {{$message}} @enderror</div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            @if($post->shared_post_id)
            <a>
                <i class="bi bi-image fs-3" onclick="$("#image").click();"></i>
            </a>
            <div class="d-none">
                <input type="file" name="image" id="image" />
            </div>
            @endif
        </div>
        <div class="col pt-4" id="imgCnt">
            @if($post->image)
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="1" name="rem_image" id="rem_image">
                <label class="form-check-label" for="rem_image">
                    Remove Image
                </label>
            </div>
            <img id="img_preview" name="img_preview" class="img-fluid" src="{{ Storage::url($post->image) }}" alt="img_preview" />
            @else
            <img id="img_preview" name="img_preview" class="img-fluid d-none" src="" alt="img_preview" />
            @endif
            @if($post->shared_post_id>0)
            <div class="row">
                <div class="col">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="1" name="rem_post" id="rem_post">
                        <label class="form-check-label" for="rem_post">
                            Remove Shared Post
                        </label>
                    </div>
                </div>
            </div>
            @endif
            @if($post->shared_post_id>0&&$post->sharedPost)
            <!-- Start of shared post  -->
            <div class="row mt-2">
                <div class="col d-flex align-items-center">
                    <img width="50" height="50" class="rounded-circle me-2 mt-2" 
                    src="
                    @if($post->sharedPost->user->profile_pic) 
                    {{ Storage::url($post->sharedPost->user->profile_pic) }} 
                    @else 
                    {{ "https://res.cloudinary.com/dfv2lwp9b/image/upload/v1650258536/user-ph_nyau61.jpg" }}
                    @endif" alt="" />
                    <div>
                        <a class="link-dark" href="{{ route("users.show",["user"=>$post->sharedPost->user->id]) }}">
                            <b>{{ $post->sharedPost->user->full_name; }}</b>
                        </a>
                        <br>
                        <span class="text-secondary fw-light">
                            {{ date("F d, Y h:i a", strtotime($post->sharedPost->created_at)) }}
                        </span>
                    </div>
                </div>
            </div>
            <div class="row mt-1">
                <div class="col fs-5 ps-5">
                    <a class="content ms-4" href="{{ route("posts.show",["post"=> $post->sharedPost->id]) }}">
                        {{ html_entity_decode($post->sharedPost->content) }}
                    </a>
                </div>
            </div>
            @if($post->sharedPost->image)
            <div class="row mt-4">
                <div class="col">
                    <img class="img-fluid" src="{{ Storage::url($post->sharedPost->image) }}" alt="">
                </div>
            </div>
            @endif
            <!-- end of shared post -->
            @elseif($post->shared_post_id>0&&!$post->sharedPost)
            <div class="row">
                <div class="col">
                    <h6 class="mt-4 text-center text-secondary">404 not found. The shared post has been deleted.</h6>
                </div>
            </div>
            @endif
        </div>
        <div class="col">
            <div class="mt-2 float-end">
                <button type="submit" class="btn btn-success">
                    <i class="bi bi-save"></i>
                    Save
                </button>
                &nbsp;&nbsp;
                <a href="{{ route("posts.show",["post" => $post->id]) }}" class="btn btn-danger">
                    <i class="bi bi-x"></i>
                    Cancel
                </a>
            </div>
        </div>
    </div>
</div>
<div class="position-fixed top-0 start-50 end-0 p-3" style="z-index: 11">
    <div id="msgToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
            <strong class="me-auto">Microblog</strong>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body" id="msgToastCnt"></div>
    </div>
</div>
<script>
    $(document).ready(function(){
        const toast = new bootstrap.Toast(document.getElementById("msgToast"));
        const readURL = (input) => {
            if(input.files && input.files[0]["type"].split("/")[0] === "image"){
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $("#img_preview").attr("src", e.target.result);
                        $("#img_preview").removeClass("d-none");
                    }
                    reader.readAsDataURL(input.files[0]);
                }
                else{
                    $("#img_preview").addClass("d-none");
                }
            }
            else{
                $("#image").val("");
                $("#msgToastCnt").html("Please select an image!");
                toast.show();
            }
        }
        $("#image").change(function(e){
          readURL(this);
      });
    });
</script>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.dashboard')
@section("title","View Post")
@section("main_content")
<div class="container">
	<div class="row">
		<div class="col">
			<div class="row mt-2">
				<div class="col d-flex align-items-center post">
					<img width="50" height="50" class="rounded-circle me-2 mt-2" 
					src="
					@if($post->user->profile_pic) 
					{{ Storage::url($post->user->profile_pic) }} 
					@else 
					{{ 'https://res.cloudinary.com/dfv2lwp9b/image/upload/v1650258536/user-ph_nyau61.jpg' }}
					@endif" alt="" />
					<div class="poster-container">
						<a class="link-dark name" href="{{ route("users.show",["user"=> $post->user->id]) }}">
							<b>{{ $post->user->full_name; }}</b>
						</a>
						<br>
						<span class="text-secondary fw-light date">
							{{ date("F d, Y h:i a", strtotime($post->created_at)) }}
						</span>
					</div>
				</div>
				@if(Auth::user()->id === $post->user_id)
				<div class="col d-flex align-items-center justify-content-end">
					<div class="btn-group">
						<button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown"aria-expanded="false">
							<i class="bi bi-three-dots"></i>
						</button>
						<ul class="dropdown-menu dropdown-menu-end">
							<li>
								<a class="dropdown-item" href="{{ route("posts.edit",['post'=> $post->id]) }}">
									Edit
								</a>
							</li>
							<li>
								<hr class="dropdown-divider">
							</li>
							<li>
								<form id="delPostFrm" method="post" action="{{ route("posts.destroy",["post"=> $post->id]) }}">
									@csrf
									@method("DELETE")
									<a role="button" class="dropdown-item delBtn" id="delPostBtn">Delete</a>
								</form>
							</li>
						</ul>
					</div>
				</div>
				@endif
			</div>
			<div class="row justify-content-center">
				<div class="col-11 px-4">
					<div class="row mt-1">
						<div class="col fs-4">{{ $post->content }}</div>
					</div>
					@if($post->image)
					<div class="row mt-4">
						<div class="col">
							<img class="img-fluid" src="{{ Storage::url($post->image) }}" alt="">
						</div>
					</div>
					@endif
					@if($post->shared_post_id>0)
					<!-- Start of shared post  -->
					@if($post->sharedPost)
					<div class="container">
						<div class="row mt-2">
							<div class="col d-flex align-items-center">
								<img width="50" height="50" class="rounded-circle me-2 mt-2" 
								src="
								@if($post->sharedPost->user->profile_pic) 
								{{ Storage::url($post->sharedPost->user->profile_pic) }} 
								@else 
								{{ 'https://res.cloudinary.com/dfv2lwp9b/image/upload/v1650258536/user-ph_nyau61.jpg' }}
								@endif" alt="" />
								<div>
									<a class="link-dark" href="{{ route("users.show",["user"=>$post->sharedPost->user->id]) }}">
										<b>{{ $post->sharedPost->user->full_name; }}</b>
									</a>
									<br>
									<span class="text-secondary fw-light">
										{{ date("F d, Y h:i a", strtotime($post->sharedPost->created_at)) }}
									</span>
								</div>
							</div>
						</div>
						<div class="row mt-1">
							<div class="col fs-5">
								<a class="content" href="{{ route("posts.show",['post'=> $post->sharedPost->id]) }}">
									{{ html_entity_decode($post->sharedPost->content) }}
								</a>
							</div>
						</div>
						@if($post->sharedPost->image)
						<div class="row mt-4">
							<div class="col">
								<img class="img-fluid" src="{{ Storage::url($post->sharedPost->image) }}" alt="">
							</div>
						</div>
						@endif
					</div>
					@else
					<div class="row">
						<div class="col">
							<h6 class="mt-4 text-center text-secondary">404 not found. The shared post has been deleted.
							</h6>
						</div>
					</div>
					@endif
					<!-- end of shared post -->
					@endif
					<div class="row my-4">
						@php
						$btnClass = "btn-outline-success";
						$icn = "hand-thumbs-up";
						$action = route("likes.store");
						$content = "Like";
						if($post->liked_by_user){
							$content = "Liked";
							$btnClass = "btn-success";
							$icn = "hand-thumbs-up-fill";
							$action = route("likes.destroy",["like" => $post->liked_by_user->id]);
						}
						@endphp
						<form class="col" method="post" action="{{ $action }}">
							@csrf
							@if($post->liked_by_user)
							@method("DELETE")
							@else
							<input type="hidden" name="post_id" id="post_id" value="{{ $post->id }}" />
							@endif
							<button type="submit" class="btn {{ $btnClass }}">
								<i class="bi bi-{{$icn}}"></i>
								{{ $content }}
								@if($post->no_of_likes>0)
								{{ $post->no_of_likes }}
								@endif
							</button>
							<button type="button" class="btn btn-secondary my-4 shareBtn" id="share{{$post->id}}">
								<i class="bi bi-share-fill"></i>
								&nbsp;&nbsp;Share
							</button>
						</form>
					</div>
				</div>
			</div>
			<hr>
			@include('flash_message')
			<form method="post" class="mb-4" action="{{ route("comments.store") }}">
				@csrf
				<input type="hidden" name="post_id" value="{{ $post->id }}" />
				<div class="row">
					<div class="col">
						<textarea class="form-control @error("content") {{"is-invalid"}} @enderror"
						placeholder="Leave a comment here" 
						name="content" 
						id="content" rows="4">{{ old("content") }}</textarea>
						<div class="text-danger mt-1">@error("content") {{$message}} @enderror</div>
					</div>
				</div>
				<div class="row">
					<div class="col mt-2">
						<button type="submit" class="btn btn-primary float-end">
							Add Comment
						</button>
					</div>
				</div>
			</form>
			@foreach($comments as $comment)
			<div class="row">
				<div class="col">
					<div class="row mt-2">
						<div class="col d-flex align-items-center">
							<img width="40" height="40" class="rounded-circle me-2 mt-2" src="
							@if($comment->user->profile_pic) 
							{{ Storage::url($comment->user->profile_pic) }} 
							@else 
							{{ 'https://res.cloudinary.com/dfv2lwp9b/image/upload/v1650258536/user-ph_nyau61.jpg' }}
							@endif" alt="" />
							<div style="line-height: 14px;">
								<a class="link-dark comment name" href="{{ route("users.show",["user"=>$post->user->id]) }}">
									<b>{{ $comment->user->full_name; }}</b>
								</a>
								<br>
								<span class="text-secondary fw-light comment date">
									{{ date("F d, Y h:i a", strtotime($comment->created_at)) }}
								</span>
							</div>
						</div>
						@can("update",$comment)
						<div class="col d-flex justify-content-end">
							<div class="btn-group">
								<button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
									<i class="bi bi-three-dots"></i>
								</button>
								<ul class="dropdown-menu dropdown-menu-end">
									<li>
										<a class="dropdown-item"  href="{{ route("comments.edit",['comment'=> $comment->id]) }}">
											Edit
										</a>
									</li>
									<li>
										<hr class="dropdown-divider">
									</li>
									<li>
										<form id="delCommentFrm{{$comment->id}}" 
											method="post" 
											action="{{ route("comments.destroy",["comment"=> $comment->id]) }}">
											@csrf
											@method("DELETE")
											<a role="button" class="dropdown-item delCommentBtn" id="del{{$comment->id}}">
												Delete
											</a>
										</form>
									</li>
								</ul>
							</div>
						</div>
						@endcan
					</div>
					<div class="row mt-2 justify-content-center">
						<div class="col-11 fs-6 ps-3">
							{{ html_entity_decode($comment->content) }}
						</div>
					</div>
				</div>
			</div>
			<hr>
			@endforeach
			<div class="row">
				<div class="col">
					{!! $comments->withQueryString()->links('pagination::bootstrap-5') !!}
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="delPostConfMdl" aria-hidden="true" tabindex="-1">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalToggleLabel">Confirm Delete</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				Are you sure you want to delete post?
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" id="delPostYesBtn">Yes</button>
				<button type="button" class="btn" data-bs-dismiss="modal">No</button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="delCommentConfMdl" aria-hidden="true" tabindex="-1">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalToggleLabel">Confirm Delete</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				Are you sure you want to delete comment?
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" id="delCommentYesBtn">Yes</button>
				<button type="button" class="btn" data-bs-dismiss="modal">No</button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="shareMdl" aria-hidden="true" tabindex="-1">
	<div class="modal-dialog modal-lg modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Share Post</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<form id="shareFrm" method="post" action="{{ route('posts.store') }}">
					@csrf
					<input type="hidden" id="shared_post_id" name="shared_post_id" value="{{ $post->id }}" />
					<textarea 
					class="form-control @error('shared_content') {{'is-invalid'}} @enderror"
					name="shared_content" id="shared_content" rows="5">{{ old("shared_content") }}</textarea>
					<div class="invalid-feedback">@error('shared_content') {{$message}} @enderror</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" id="shareBtn">Share</button>
				<button type="button" class="btn" data-bs-dismiss="modal">Cancel</button>
			</div>
		</div>
	</div>
</div>
<script>
	$(document).ready(function() {
		let id = 0;
		const delPostConfMdl = new bootstrap.Modal(document.getElementById('delPostConfMdl'), {
			keyboard: false,
			backdrop: 'static',
		});
		const delCommentConfMdl = new bootstrap.Modal(document.getElementById('delCommentConfMdl'), {
			keyboard: false,
			backdrop: 'static',
		});
		const shareMdl = new bootstrap.Modal(document.getElementById('shareMdl'), {
			keyboard: false,
			backdrop: 'static',
		});
		$("#delPostBtn").click(function(e) {
			delPostConfMdl.show();
		});
		$("#delPostYesBtn").click(function() {
			$("#delPostFrm").submit();
			delPostConfMdl.hide();
		});
		$(".delCommentBtn").click(function(e) {
			id = $(this).attr("id").replace("del", "");
			delCommentConfMdl.show();
		});
		$("#delCommentYesBtn").click(function() {
			$("#delCommentFrm" + id).submit();
			delCommentConfMdl.hide();
		});
		$(".shareBtn").click(function() {
			const shared_post_id = $(this).attr("id").replace("share", "");
			$("#shared_post_id").val(shared_post_id);
			$("#shared_content").removeClass("is-invalid");
			shareMdl.show();
		});
		$("#shareBtn").click(function() {
			$("#shareFrm").submit();
		});
		@error('shared_content')
		shareMdl.show();
		@enderror
	});
</script>
@endsection