routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FollowerController;
use App\Http\Controllers\LikedPostController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/register", function () {
    return view("auth.register");
})->name("register.view");

Route::get("/login", function () {
    if (Auth::check()) {
        return redirect()->route("home");
    } else {
        return view("auth.login");
    }
})->name("login");

Route::controller(UserController::class)->group(function () {
    Route::post("/register", "store")->name("register.post");

    Route::get("/activate/{token}", "activation")->name("activation");

    Route::post("/resend-activation", "resendActivation")->name("resend-activation");

    Route::post("/login", "login");
});

Route::middleware(["auth"])->group(function () {
    Route::get("/", [PostController::class,"index"])->name("home");

    Route::controller(UserController::class)->group(function () {
        Route::get("/search/users", "search")->name("users.search");
        Route::patch("/change-password/{user}", "updatePassword")->name("users.change-password");
    });

    Route::resource("users", UserController::class)->only([
        "show","edit","update"
    ]);

    Route::controller(FollowerController::class)->group(function () {
        Route::get("/{id}/followers", "follow")->name("users.followers");
        Route::get("/{id}/following", "follow")->name("users.following");
        Route::post("follow", "store")->name("follow");
        Route::delete("follow", "destroy")->name("unfollow");
    });

    Route::controller(PostController::class)->group(function () {
        Route::get("/search/posts", "search")->name("posts.search");
    });

    Route::resource("posts", PostController::class)->except([
        "index",
        "create"
    ]);



    Route::resource("comments", CommentController::class)->except([
        "index", "create", "show"
    ]);
    Route::resource("likes", LikedPostController::class)->only([
        "store","destroy"
    ]);



    Route::post("/logout", [UserController::class,"logout"])->name("logout");
});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Comment extends Model
{
    use SoftDeletes;

    /**
     * Get Post owning the comment
     *
     * @return void
     */
    public function post()
    {
        return $this->belongsTo(Post::class);
    }
    /**
     * Get user owner
     *
     * @return void
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use App\Models\Comment;
use App\Http\Requests\StoreCommentRequest;
use App\Http\Requests\UpdateCommentRequest;

class CommentController extends Controller
{
    /**
     * Adding built-in middleware on class construction
     */
    public function __construct()
    {
        $this->middleware("can:delete,comment")->only(['edit','delete']);
    }
    /**
     * Store Comment
     *
     * @param StoreCommentRequest $req
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreCommentRequest $req)
    {
        $safe = $req->safe();
        $comment = new Comment();
        $comment->content = $safe->content;
        $comment->post_id = $safe->post_id;
        $comment->user_id = Auth::user()->id;
        $comment->save();

        return back()->with("success", "Comment posted successfully!");
    }
    /**
     * Edit comment
     *
     * @param Comment $comment
     * @return \Illuminate\Contracts\View\View
     */
    public function edit(Comment $comment)
    {
        return view('comments.edit', compact("comment"));
    }
    /**
     * Updating Comment
     *
     * @param UpdateCommentRequest $req
     * @param Comment $comment
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateCommentRequest $req, Comment $comment)
    {
        $safe = $req->safe();
        $comment->content = $safe->content;
        $comment->save();

        return redirect()->route(
            "posts.show",
            [
                "post" => $comment->post_id
            ]
        )->with("success", "Comment Updated!");
    }
    /**
     * Deleting Comment
     *
     * @param Comment $comment
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Comment $comment)
    {
        $comment->delete();

        return back()->with("success", "Comment Deleted!");
    }
}

resources/views/comments/edit.blade.php
@extends("layouts.dashboard")
@section("title","Edit Comment")
@section("main_content")
<br>
<form method="post" action="{{ route("comments.update",["comment" => $comment->id]) }}" class="container-fluid">
    @csrf
    @method("PATCH")
    <div class="row">
        <div class="col mb-3">
            @include("flash_message")
            <textarea 
            class="form-control @error("content") {{"is-invalid"}} @enderror" 
            id="content" 
            rows="8" 
            name="content">@if(old("content")){{ old("content") }}@else{{ $comment->content }}@endif</textarea>
            <div class="text-danger mt-1">
                @error("content") 
                {{$message}} 
                @enderror
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="mt-2 float-end">
                <a href="{{ url(
                    route("posts.show",
                    ["post" => $comment->post_id]
                    )) }}" class="btn btn-danger">
                    <i class="bi bi-x-lg"></i>
                    &nbsp;&nbsp;Cancel
                </a>
                &nbsp;&nbsp;
                <button type="submit" class="btn btn-success">
                    <i class="bi bi-save"></i>
                    &nbsp;&nbsp;Save
                </button>
            </div>
        </div>
    </div>
</div>
@endsection